"""empty message

Revision ID: 210897743004
Revises: 13dd3914e8d9
Create Date: 2022-05-13 15:08:39.649765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210897743004'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    # ### end Alembic commands ###
