"""empty message

Revision ID: 212517afa599
Revises: 
Create Date: 2022-05-16 13:50:37.574443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212517afa599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legendaryweapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    op.drop_table('user')
    op.drop_table('legendaryweapon')
    # ### end Alembic commands ###
