"""empty message

Revision ID: 4851d55ba22f
Revises: 212517afa599
Create Date: 2022-05-16 14:27:36.307294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4851d55ba22f'
down_revision = '212517afa599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon', sa.Column('location_description', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'location_description')
    # ### end Alembic commands ###
