"""empty message

Revision ID: 755f37a45476
Revises: 946f6b679afa
Create Date: 2022-05-31 15:11:52.127124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755f37a45476'
down_revision = '946f6b679afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exotic_weapon', sa.Column('no_video_text', sa.String(length=100), nullable=True))
    op.add_column('legendary_weapon', sa.Column('no_video_text', sa.String(length=100), nullable=True))
    op.add_column('rare_weapon', sa.Column('no_video_text', sa.String(length=100), nullable=True))
    op.add_column('uncommon_weapon', sa.Column('no_video_text', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uncommon_weapon', 'no_video_text')
    op.drop_column('rare_weapon', 'no_video_text')
    op.drop_column('legendary_weapon', 'no_video_text')
    op.drop_column('exotic_weapon', 'no_video_text')
    # ### end Alembic commands ###
