"""empty message

Revision ID: 946f6b679afa
Revises: e8701dfff594
Create Date: 2022-05-26 17:37:21.322712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946f6b679afa'
down_revision = 'e8701dfff594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exotic_weapon', sa.Column('video_credit', sa.String(length=100), nullable=True))
    op.add_column('legendary_weapon', sa.Column('video_credit', sa.String(length=100), nullable=True))
    op.add_column('rare_weapon', sa.Column('video_credit', sa.String(length=100), nullable=True))
    op.add_column('uncommon_weapon', sa.Column('location_video', sa.String(length=200), nullable=True))
    op.add_column('uncommon_weapon', sa.Column('video_credit', sa.String(length=100), nullable=True))
    op.drop_column('uncommon_weapon', 'location_Img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uncommon_weapon', sa.Column('location_Img', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('uncommon_weapon', 'video_credit')
    op.drop_column('uncommon_weapon', 'location_video')
    op.drop_column('rare_weapon', 'video_credit')
    op.drop_column('legendary_weapon', 'video_credit')
    op.drop_column('exotic_weapon', 'video_credit')
    # ### end Alembic commands ###
