"""empty message

Revision ID: a4df1422adb9
Revises: e7acb875499b
Create Date: 2022-05-23 18:37:49.339121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4df1422adb9'
down_revision = 'e7acb875499b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legendary_weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rare_weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uncommon_weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('commonweapon')
    op.drop_table('rareweapon')
    op.drop_table('legendaryweapon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legendaryweapon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weapon_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('weapon_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_lore', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('location_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='legendaryweapon_pkey')
    )
    op.create_table('rareweapon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weapon_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('weapon_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_lore', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('location_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rareweapon_pkey')
    )
    op.create_table('commonweapon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weapon_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('weapon_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_class', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weapon_lore', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('location_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='commonweapon_pkey')
    )
    op.drop_table('uncommon_weapon')
    op.drop_table('rare_weapon')
    op.drop_table('legendary_weapon')
    op.drop_table('common_weapon')
    # ### end Alembic commands ###
