"""empty message

Revision ID: d7a4e951e5d2
Revises: e011f4e373e0
Create Date: 2022-05-26 13:30:11.844798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a4e951e5d2'
down_revision = 'e011f4e373e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exotic_weapon', sa.Column('location_Img', sa.String(length=100), nullable=False))
    op.add_column('exotic_weapon', sa.Column('weapon_Img', sa.String(length=100), nullable=False))
    op.add_column('legendary_weapon', sa.Column('location_Img', sa.String(length=100), nullable=False))
    op.add_column('legendary_weapon', sa.Column('weapon_Img', sa.String(length=100), nullable=False))
    op.add_column('rare_weapon', sa.Column('location_Img', sa.String(length=100), nullable=False))
    op.add_column('rare_weapon', sa.Column('weapon_Img', sa.String(length=100), nullable=False))
    op.add_column('uncommon_weapon', sa.Column('location_Img', sa.String(length=100), nullable=False))
    op.add_column('uncommon_weapon', sa.Column('weapon_Img', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uncommon_weapon', 'weapon_Img')
    op.drop_column('uncommon_weapon', 'location_Img')
    op.drop_column('rare_weapon', 'weapon_Img')
    op.drop_column('rare_weapon', 'location_Img')
    op.drop_column('legendary_weapon', 'weapon_Img')
    op.drop_column('legendary_weapon', 'location_Img')
    op.drop_column('exotic_weapon', 'weapon_Img')
    op.drop_column('exotic_weapon', 'location_Img')
    # ### end Alembic commands ###
