"""empty message

Revision ID: e7acb875499b
Revises: 32985ec550ec
Create Date: 2022-05-23 16:26:10.189291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7acb875499b'
down_revision = '32985ec550ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commonweapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rareweapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon_name', sa.String(length=120), nullable=False),
    sa.Column('weapon_type', sa.String(length=20), nullable=False),
    sa.Column('weapon_class', sa.String(length=20), nullable=False),
    sa.Column('weapon_lore', sa.String(length=1000), nullable=False),
    sa.Column('location_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rareweapon')
    op.drop_table('commonweapon')
    # ### end Alembic commands ###
