"""empty message

Revision ID: e8701dfff594
Revises: d7a4e951e5d2
Create Date: 2022-05-26 14:01:21.289864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8701dfff594'
down_revision = 'd7a4e951e5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exotic_weapon', sa.Column('location_video', sa.String(length=200), nullable=True))
    op.alter_column('exotic_weapon', 'weapon_Img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_column('exotic_weapon', 'location_Img')
    op.add_column('legendary_weapon', sa.Column('location_video', sa.String(length=200), nullable=True))
    op.alter_column('legendary_weapon', 'weapon_Img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_column('legendary_weapon', 'location_Img')
    op.add_column('rare_weapon', sa.Column('location_video', sa.String(length=200), nullable=True))
    op.alter_column('rare_weapon', 'weapon_Img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_column('rare_weapon', 'location_Img')
    op.alter_column('uncommon_weapon', 'location_Img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('uncommon_weapon', 'weapon_Img',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uncommon_weapon', 'weapon_Img',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('uncommon_weapon', 'location_Img',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('rare_weapon', sa.Column('location_Img', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('rare_weapon', 'weapon_Img',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('rare_weapon', 'location_video')
    op.add_column('legendary_weapon', sa.Column('location_Img', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('legendary_weapon', 'weapon_Img',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('legendary_weapon', 'location_video')
    op.add_column('exotic_weapon', sa.Column('location_Img', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('exotic_weapon', 'weapon_Img',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('exotic_weapon', 'location_video')
    # ### end Alembic commands ###
