"""empty message

Revision ID: fa2a478ce990
Revises: 755f37a45476
Create Date: 2022-05-31 16:01:43.919698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2a478ce990'
down_revision = '755f37a45476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exotic_weapon', 'video_credit')
    op.drop_column('exotic_weapon', 'no_video_text')
    op.drop_column('legendary_weapon', 'video_credit')
    op.drop_column('legendary_weapon', 'no_video_text')
    op.drop_column('rare_weapon', 'video_credit')
    op.drop_column('rare_weapon', 'no_video_text')
    op.drop_column('uncommon_weapon', 'video_credit')
    op.drop_column('uncommon_weapon', 'no_video_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uncommon_weapon', sa.Column('no_video_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('uncommon_weapon', sa.Column('video_credit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('rare_weapon', sa.Column('no_video_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('rare_weapon', sa.Column('video_credit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('legendary_weapon', sa.Column('no_video_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('legendary_weapon', sa.Column('video_credit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exotic_weapon', sa.Column('no_video_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('exotic_weapon', sa.Column('video_credit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
